# Generated by Django 3.2.4 on 2021-06-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencebook',
            options={'verbose_name': 'Идентификатор cправочника', 'verbose_name_plural': 'Идентификатор cправочника'},
        ),
        migrations.RemoveField(
            model_name='referencebook',
            name='date',
        ),
        migrations.RemoveField(
            model_name='referencebook',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='referencebook',
            name='name',
        ),
        migrations.RemoveField(
            model_name='referencebook',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='referencebook',
            name='version',
        ),
        migrations.AddField(
            model_name='referencebook',
            name='ident',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReferenceBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование справочника')),
                ('short_name', models.CharField(max_length=50, verbose_name='Короткое наименование')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('version', models.CharField(max_length=200, unique=True, verbose_name='Версия')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Начало действия справочника')),
                ('ident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_book.referencebook', verbose_name='Идентификатор cправочника')),
            ],
            options={
                'verbose_name': 'Данные справочник',
                'verbose_name_plural': 'Данные справочник',
            },
        ),
    ]
