# Generated by Django 3.2.4 on 2021-06-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0002_auto_20210614_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencebook',
            name='ident',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
