# Generated by Django 3.2.4 on 2021-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0003_alter_referencebook_ident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencebook',
            options={'verbose_name': 'Cправочник', 'verbose_name_plural': 'Cправочника'},
        ),
        migrations.RemoveField(
            model_name='itemreferencebook',
            name='desc_value',
        ),
        migrations.AlterField(
            model_name='referencebook',
            name='ident',
            field=models.CharField(max_length=200, unique=True, verbose_name='Идентификатор cправочника'),
        ),
        migrations.AlterField(
            model_name='referencebookdata',
            name='date',
            field=models.DateField(verbose_name='Начало действия справочника'),
        ),
        migrations.AlterField(
            model_name='referencebookdata',
            name='version',
            field=models.CharField(max_length=200, verbose_name='Версия'),
        ),
        migrations.AlterUniqueTogether(
            name='referencebookdata',
            unique_together={('date',)},
        ),
    ]
