# Generated by Django 3.2.4 on 2021-06-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0004_auto_20210614_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencebook',
            name='ident',
        ),
        migrations.AlterUniqueTogether(
            name='referencebookdata',
            unique_together={('ident', 'version')},
        ),
    ]
