# Generated by Django 3.2.4 on 2021-06-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0006_auto_20210615_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencebook',
            options={},
        ),
        migrations.AddField(
            model_name='referencebookdata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='referencebookdata',
            name='date',
            field=models.DateField(help_text='Пример даты - 15.06.2102', verbose_name='Начало действия справочника'),
        ),
        migrations.AlterField(
            model_name='referencebookdata',
            name='reference_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='reference_book.referencebook', verbose_name='Идентификатор cправочника'),
        ),
    ]
