# Generated by Django 3.2.4 on 2021-06-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0008_alter_referencebookdata_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreferencebook',
            name='reference_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_book.referencebookdata', verbose_name='Версия справочника'),
        ),
    ]
