# Generated by Django 3.2.4 on 2021-06-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0010_auto_20210617_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencebook',
            options={'verbose_name': 'Данные справочник', 'verbose_name_plural': 'Данные справочник'},
        ),
        migrations.AlterModelOptions(
            name='referencebookdata',
            options={'verbose_name': 'Версия справочника', 'verbose_name_plural': 'Версии справочника'},
        ),
        migrations.AlterUniqueTogether(
            name='itemreferencebook',
            unique_together={('reference_book', 'code', 'value')},
        ),
    ]
